/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as AuthedDashboardIndexRouteImport } from './routes/_authed/dashboard/index'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthedDashboardSectorsRouteImport } from './routes/_authed/dashboard/sectors'
import { Route as AuthedDashboardMacrosRouteImport } from './routes/_authed/dashboard/macros'
import { Route as AuthedDashboardCompareRouteImport } from './routes/_authed/dashboard/compare'
import { Route as AuthedDashboardDIdRouteImport } from './routes/_authed/dashboard/d.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardIndexRoute = AuthedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardSectorsRoute = AuthedDashboardSectorsRouteImport.update({
  id: '/dashboard/sectors',
  path: '/dashboard/sectors',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardMacrosRoute = AuthedDashboardMacrosRouteImport.update({
  id: '/dashboard/macros',
  path: '/dashboard/macros',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardCompareRoute = AuthedDashboardCompareRouteImport.update({
  id: '/dashboard/compare',
  path: '/dashboard/compare',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardDIdRoute = AuthedDashboardDIdRouteImport.update({
  id: '/dashboard/d/$id',
  path: '/dashboard/d/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/api/inngest': typeof ApiInngestRoute
  '/': typeof AuthedIndexRoute
  '/dashboard/compare': typeof AuthedDashboardCompareRoute
  '/dashboard/macros': typeof AuthedDashboardMacrosRoute
  '/dashboard/sectors': typeof AuthedDashboardSectorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/d/$id': typeof AuthedDashboardDIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/api/inngest': typeof ApiInngestRoute
  '/': typeof AuthedIndexRoute
  '/dashboard/compare': typeof AuthedDashboardCompareRoute
  '/dashboard/macros': typeof AuthedDashboardMacrosRoute
  '/dashboard/sectors': typeof AuthedDashboardSectorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/dashboard': typeof AuthedDashboardIndexRoute
  '/dashboard/d/$id': typeof AuthedDashboardDIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/api/inngest': typeof ApiInngestRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/dashboard/compare': typeof AuthedDashboardCompareRoute
  '/_authed/dashboard/macros': typeof AuthedDashboardMacrosRoute
  '/_authed/dashboard/sectors': typeof AuthedDashboardSectorsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/_authed/dashboard/': typeof AuthedDashboardIndexRoute
  '/_authed/dashboard/d/$id': typeof AuthedDashboardDIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/api/inngest'
    | '/'
    | '/dashboard/compare'
    | '/dashboard/macros'
    | '/dashboard/sectors'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard'
    | '/dashboard/d/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/api/inngest'
    | '/'
    | '/dashboard/compare'
    | '/dashboard/macros'
    | '/dashboard/sectors'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/dashboard'
    | '/dashboard/d/$id'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/api/inngest'
    | '/_authed/'
    | '/_authed/dashboard/compare'
    | '/_authed/dashboard/macros'
    | '/_authed/dashboard/sectors'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/_authed/dashboard/'
    | '/_authed/dashboard/d/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiInngestRoute: typeof ApiInngestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/': {
      id: '/_authed/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard/sectors': {
      id: '/_authed/dashboard/sectors'
      path: '/dashboard/sectors'
      fullPath: '/dashboard/sectors'
      preLoaderRoute: typeof AuthedDashboardSectorsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/macros': {
      id: '/_authed/dashboard/macros'
      path: '/dashboard/macros'
      fullPath: '/dashboard/macros'
      preLoaderRoute: typeof AuthedDashboardMacrosRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/compare': {
      id: '/_authed/dashboard/compare'
      path: '/dashboard/compare'
      fullPath: '/dashboard/compare'
      preLoaderRoute: typeof AuthedDashboardCompareRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard/d/$id': {
      id: '/_authed/dashboard/d/$id'
      path: '/dashboard/d/$id'
      fullPath: '/dashboard/d/$id'
      preLoaderRoute: typeof AuthedDashboardDIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedDashboardCompareRoute: typeof AuthedDashboardCompareRoute
  AuthedDashboardMacrosRoute: typeof AuthedDashboardMacrosRoute
  AuthedDashboardSectorsRoute: typeof AuthedDashboardSectorsRoute
  AuthedDashboardIndexRoute: typeof AuthedDashboardIndexRoute
  AuthedDashboardDIdRoute: typeof AuthedDashboardDIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedDashboardCompareRoute: AuthedDashboardCompareRoute,
  AuthedDashboardMacrosRoute: AuthedDashboardMacrosRoute,
  AuthedDashboardSectorsRoute: AuthedDashboardSectorsRoute,
  AuthedDashboardIndexRoute: AuthedDashboardIndexRoute,
  AuthedDashboardDIdRoute: AuthedDashboardDIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiInngestRoute: ApiInngestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
